package com.cc.oem.common.utils.message.msg;

/**
 * @author wangqiang
 * @since 2018/6/30
 */
public class EmailMessage {
    private String from;
    private String fromName;
    private String to[];
    private String subject;
    private String text;

    boolean        isHtml    = true;
    boolean        multipart = true;


    public String getFrom() {
        return from;
    }


    private void setFrom(final String from) {
        this.from = from;
    }


    public String getFromName() {
        return fromName;
    }


    void setFromName(final String fromName) {
        this.fromName = fromName;
    }


    public String[] getTo() {
        return to;
    }


    void setTo(final String[] to) {
        this.to = to;
    }


    public String getSubject() {
        return subject;
    }


    void setSubject(final String subject) {
        this.subject = subject;
    }


    public String getText() {
        return text;
    }


    void setText(final String text) {
        this.text = text;
    }


    public boolean isHtml() {
        return isHtml;
    }


    void setHtml(final boolean html) {
        isHtml = html;
    }


    public boolean isMultipart() {
        return multipart;
    }


    public void setMultipart(final boolean multipart) {
        this.multipart = multipart;
    }

    public static class EmailMessageBuilder {
        /**
         * Generated by POJO Builder Generate Plugin.
         */

        private final EmailMessage instance = new EmailMessage();


        public EmailMessageBuilder withFrom(String from) {
            instance.setFrom(from);
            return this;
        }


        public EmailMessageBuilder withFromName(String fromName) {
            instance.setFromName(fromName);
            return this;
        }


        public EmailMessageBuilder withTo(String... to) {
            if (to != null && to.length > 0) {
                instance.setTo(to);
            }
            return this;
        }


        public EmailMessageBuilder withSubject(String subject) {
            instance.setSubject(subject);
            return this;
        }


        public EmailMessageBuilder withText(String text) {
            instance.setText(text);
            return this;
        }


        public EmailMessageBuilder setHtml(final boolean html) {
            instance.setHtml(html);
            return this;
        }


        public EmailMessageBuilder setMultipart(final boolean multipart) {
            instance.setMultipart(multipart);
            return this;
        }


        public EmailMessage build() {
            EmailMessage copy = new EmailMessage();
            copy.setFrom(instance.getFrom());
            copy.setSubject(instance.getSubject());
            copy.setText(instance.getText());
            copy.setTo(instance.getTo());
            copy.setFromName(instance.getFromName());
            copy.setMultipart(instance.isMultipart());
            copy.setHtml(instance.isHtml());
            return copy;
        }

    }


    public static EmailMessageBuilder builder() {
        /**
         * Generated by POJO Builder Generate Plugin.
         */
        return new EmailMessageBuilder();
    }

}
